### ISSUE TITLE
 Difference among distutils.sysconfig.get_python_inc()

### ISSUE THREAD

**Issue by wqh17101** [pypa/distutils#179] opened 2022-09-23 09:43 UTC
The issue is related to https://github.com/pypa/setuptools/issues/3605

**Comment by wqh17101** [comment] 2022-09-23 11:11
I found that
```
default_prefix:/opt/aaa/python/python-3.9.2
resolved_prefix:/opt/aa/python/python-3.9.2
 _get_python_inc_posix_python : None
_get_python_inc_from_config: /devcloud/ws/sirFh/workspace/j_VWBQ8FGA/aaa_python/third_build/python/include/python3.9
 _get_python_inc_posix_prefix: /opt/aaa/python/python-3.9.2/include/python3.9

```

**Comment by wqh17101** [comment] 2022-09-23 11:30
I found that the path in _get_python_inc_from_config is geneated by prefix which is a option of building python.
But the python can install to anywhere,maybe not the same as prefix.So this will cause this error.
Maybe we can adjust the order of https://github.com/pypa/distutils/blob/22b9bcf2e2d2a66f7dc96661312972e2f6bd9e01/distutils/sysconfig.py#L136-L140
like 
```
 return (
        _get_python_inc_posix_python(plat_specific)
        or _get_python_inc_posix_prefix(prefix
        or _get_python_inc_from_config(plat_specific, spec_prefix)
        )
    )
```

**Comment by jaraco** [comment] 2022-10-29 06:51
I believe this issue is a duplicate of #178.

**Closed by jaraco** 2022-10-29 06:51 UTC
