### ISSUE TITLE
[BUG]  CC="ccache gcc" stopped working for C++ builds since setuptools-60.0.0

### ISSUE THREAD

**Issue by bjodah** [pypa/distutils#126] opened 2022-02-22 03:33 UTC
### setuptools version

setuptools>=60.0.0

### Python version

CPython 3.9

### OS

Ubuntu 20.04 LTS

### Additional environment information

-

### Description

Running setup.py build_ext with CC set to "ccache gcc-11" causes this to happen when building a c++ extension module:
```
g++-11 gcc-11 -shared -Wl,-rpath=/opt/cpython-3.9-debug/lib -Wl,--disable-new-dtags -Wl,-rpath,/opt/sundials-5.7.0-noklu-nolapack-dbg/lib -L/opt/sundials-5.7.0-noklu-nolapack-dbg/lib -isystem /opt/sundials-5.7.0-noklu-nolapack-dbg/include build/temp.linux-x86_64-3.9-pydebug/pyodeint/_odeint.o -L/opt/cpython-3.9-debug/lib -o build/lib.linux-x86_64-3.9-pydebug/pyodeint/_odeint.cpython-39d-x86_64-linux-gnu.so
/usr/bin/ld: cannot find gcc-11: No such file or directory
```
Setting `SETUPTOOLS_USE_DISTUTILS=stdlib` yields the expected linkline:
```
g++-11 -pthread -shared -Wl,-rpath=/opt/cpython-3.9-debug/lib -Wl,--disable-new-dtags -Wl,-rpath,/opt/sundials-5.7.0-noklu-nolapack-dbg/lib -L/opt/sundials-5.7.0-noklu-nolapack-dbg/lib -isystem /opt/sundials-5.7
.0-noklu-nolapack-dbg/include build/temp.linux-x86_64-3.9-pydebug/pyodeint/_odeint.o -L/opt/cpython-3.9-debug/lib -o build/lib.linux-x86_64-3.9-pydebug/pyodeint/_odeint.cpython-39d-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.9-pydebug/pyodeint/_odeint.cpython-39d-x86_64-linux-gnu.so -> pyodeint
```

The compile comands look alright though:
`ccache gcc-11 -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -g -Og -Wall -Og -g3 -Og -g3 -isystem /opt/sundials-5.7.0-noklu-nolapack-dbg/include -fPIC -DANYODE_NO_LAPACK=1 -DNDEBUG -DBOOST_UB
LAS_TYPE_CHECK=0 -Ipyodeint/include -I/opt/cpython-3.9-debug/lib/python3.9/site-packages/numpy/core/include -Iexternal/anyode/include -I/opt/cpython-3.9-debug/include/python3.9d -c pyodeint/_odeint.cpp -o build/
temp.linux-x86_64-3.9-pydebug/pyodeint/_odeint.o -std=c++20 `

Perhaps the space between `ccache` and `g++` is unaccounted for in setuptools (own?) distutils?

### Expected behavior

-

### How to Reproduce

-

### Output

```console

```

**Comment by isuruf** [comment] 2022-03-12 17:43
Before #53, LDSHARED command was,
```
gcc -pthread -shared <rest>
```
and after #53, setting `export CC="ccache gcc"` would make LDSHARED to be,
```
ccache gcc -pthread -shared <rest>
```
When the link language was C++, distutils would look at the first word and replace it. So before #53,
it became,
```
g++ -pthread -shared <rest>
```
and after #53 it became
```
g++ gcc -pthread -shared <rest>
```

Does that make sense? I can describe in more detail if you want.

**Comment by jaraco** [comment] 2022-03-12 18:41
That clarifies. Thanks for connecting the dots.

**Comment by FFY00** [comment] 2022-03-12 18:49
The issue is this line:

https://github.com/pypa/distutils/blob/e28e150c036e8b2bd55a37df13e836e098b5f37d/distutils/sysconfig.py#L229

Which assumes `CC` and `LDSHARED` have the same number of arguments for the compiler. In reality, there's no way to safely override the compiler in `LDSHARED` when `CC` is set because we don't know what part of `LDSHARED` is the compiler, so the code is assuming `CC` and `LDSHARED` are coherent.

The good news is that here we are only dealing with the default values for `CC` and `LDSHARED`, the values from the Python interpreter `Makefile`, which are exposed in `get_config_vars`. So it shouldn't affect users, and the fix would be for the distributors to set `LDSHARED` in accordance to `CC`.

That said, given that the issue is the usage of ccache being registered as the compiler, when it is in fact just a compiler wrapper, and nothing we care or should register in the makefile data, I think the best fix would be to add way to specify compiler prefixes in the build system, so that it does not leak into `CC`.
I would recommend distributors who are building Python with ccache to manually edit the installed makefile data for sysconfig to remove ccache from `CC`.

**Comment by FFY00** [comment] 2022-03-12 18:52
In the meanwhile, we could maybe have a heuristic to try detecting this issue, particularly with ccache, and mitigate the situation for most users.

**Comment by isuruf** [comment] 2022-03-19 20:54
Fixed in https://github.com/pypa/distutils/pull/117

**Closed** 2022-03-28 00:24 UTC
Labels: bug, Needs Investigation
